# Site settings
title: Yue Harriet Huang
email: dariahuangster@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a data intelligence practioner that have contributed building innovative prediction models in solving day-to-day problems in retail optimized pricing, medical detection and financial industry using statistical learning and deep learning technologies. Topics on my site include
  my research interests, Python, and professional and personal development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://Yue1Harriet1Huang.github.io" # the base hostname & protocol for your site
twitter_username: YueHarriet
github_username:  Yue1Harriet1Huang
orcid_id: 
google_scholar_id: 

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Data Scientist"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: "https://plus.google.com/u/0/110288225974212014913"
# google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
# bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

plugins:
  - jekyll-sitemap
